@echo off
title DirtCaps /Gereksiz Silici Performans
color 4
install_wim_tweak.exe /o /l
install_wim_tweak.exe /o /c Microsoft-OneCore-CortanaComponents-Package~31bf3856ad364e35~amd64~~10.0.10586.0 /r

install_wim_tweak.exe /o /c Microsoft-Windows-Internet-Browser-Package /r
install_wim_tweak.exe /o /c Microsoft-Windows-ContactSupport /r
install_wim_tweak.exe /o /c Microsoft-WindowsFeedback" /r
install_wim_tweak.exe /o /c Microsoft-Xbox-GameCallableUI-Package /r

install_wim_tweak.exe /o /c Microsoft-Windows-OpticalMediaDisc-Package /r" /f
install_wim_tweak.exe /o /c Microsoft-Windows-Tuner-Drivers-Package /r" /f
install_wim_tweak.exe /o /c Microsoft-Windows-SUA-Package /r" /f
install_wim_tweak.exe /o /c Microsoft-Windows-SNMP-Package /r" /f 

install_wim_tweak.exe /o /c Microsoft-OneCore-AllowTelemetry /r
install_wim_tweak.exe /o /c Microsoft-Windows-DiagTrack-Internal /r
install_wim_tweak.exe /o /c Microsoft-Windows-InsiderHub-Package /r
install_wim_tweak.exe /o /c Microsoft-Windows-OneDrive /r

install_wim_tweak.exe /o /c Checkpoint-VpnPlugin-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384 /r
install_wim_tweak.exe /o /c Checkpoint-VpnPlugin-Package~31bf3856ad364e35~amd64~~6.3.9600.16384 /r
install_wim_tweak.exe /o /c F5-VpnPlugin-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384 /r
install_wim_tweak.exe /o /c F5-VpnPlugin-Package~31bf3856ad364e35~amd64~~6.3.9600.16384 /r
install_wim_tweak.exe /o /c Juniper-VpnPlugin-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384 /r
install_wim_tweak.exe /o /c Juniper-VpnPlugin-Package~31bf3856ad364e35~amd64~~6.3.9600.16384 /r

install_wim_tweak.exe /o /c Windows-Defender /r
install_wim_tweak.exe /o /c Microsoft-Windows-ContentDeliveryManager /r
install_wim_tweak.exe /o /c Microsoft-Windows-Store /r
install_wim_tweak.exe /o /c Microsoft-Windows-Holographic /r
install_wim_tweak.exe /o /c Microsoft-Windows-Internet-Browser /r
install_wim_tweak.exe /o /c Microsoft-Windows-ContactSupport /r
install_wim_tweak.exe /o /c Microsoft-PPIProjection-Package /r
install_wim_tweak.exe /o /c Microsoft-Windows-InsiderHub /r
install_wim_tweak.exe /o /c Microsoft-Windows-Cortana /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MediaViewer-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MediaViewer-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Camera-Package" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WebcamExperience-Package" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-FileManager-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-FileManager-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Store-Client-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Store-Client-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Checkpoint-VpnPlugin-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Checkpoint-VpnPlugin-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "F5-VpnPlugin-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "F5-VpnPlugin-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Juniper-VpnPlugin-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Juniper-VpnPlugin-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-VpnPlugins-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-VpnPlugins-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "SonicWALL-VpnPlugin-Package~31bf3856ad364e35~amd64~~6.3.9600.16384" /r
install_wim_tweak.exe /o /c "SonicWALL-VpnPlugin-Package~31bf3856ad364e35~amd64~en-US~6.3.9600.16384" /r

install_wim_tweak.exe /o /c "Microsoft-Windows-Internet" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Cortana" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Search2" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SearchEngine" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-RetailDemo" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-ContactSupport" /r
install_wim_tweak.exe /o /c "Microsoft-PPIProjection" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Backup" /r
install_wim_tweak.exe /o /c "Windows-Defender" /r
install_wim_tweak.exe /o /c "Microsoft-Xbox" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TroubleShooting" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-TroubleShooting" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-LanguageFeatures" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Legacy" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-SpeechComponents" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Gaming" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Indexer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-BioEnrollment" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Biometrics" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Printing-XPSServices" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Xps" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Geolocation" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Compression" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-BusinessScanning" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MediaPlayer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WindowsMediaPlayer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-VirtualPC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-VirtualXP" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SystemRestore" /r


install_wim_tweak.exe /o /c "Microsoft-Windows-WebcamExperience" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-PeerDist" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SnippingTool" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Store" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Common-Modem" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Multimedia-MFPMP" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-NetworkDiagnostics" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Network-QoS" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Proximity" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Printing-PrintToPDFServices" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-ShareMedia" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Telnet" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TabletPC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SNMP" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Skype" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Sensors" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Tethering" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-UserDataAccess" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Wallet" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-WebService" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-3DAudio" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-AppCompat" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-BITS" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Browser" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Casting" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-CoreSystem-DebugTransports" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Help" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WMIPerf" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-IIS-WebServer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Killbits" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Lxss" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Media-Streaming" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MiracastView" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MobilePC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Shell-HomeGroup" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Network-Connectivity-Assistant" /r
install_wim_tweak.exe /o /c "Media-FaceAnalysis" /r
install_wim_tweak.exe /o /c "Media-Ocr" /r
install_wim_tweak.exe /o /c "Microsoft-Mobile" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-AllJoyn" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-AllowTelemetry" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-BITS" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-CameraCaptureUI" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Connectivity-NFC" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Connectivity-Serial" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-DebugCore" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-InkPlatform" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Maps" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Miracast" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Multimedia-CastingCommon" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Multimedia-CastingReceiver" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Multimedia-CastingTransmitter" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-NowPlayingSessionManager" /r
install_wim_tweak.exe /o /c "Server-Help" /r
install_wim_tweak.exe /o /c "Sensors-Universal" /r
install_wim_tweak.exe /o /c "MultiPoint-Help" /r

install_wim_tweak.exe /o /c "DeviceAccess" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-ESENT" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-DirectoryServices-ADAM" /r
install_wim_tweak.exe /o /c "microsoft-windows-directoryservices-adam" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WinRT" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-International" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SenseClient" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-ApplicationModel-Sync" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-DeviceSync" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-EnterpriseClientSync" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-ShareMedia" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Telnet" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-RDC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-PerformanceCounters" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-PeerToPeer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-ParentalControls" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-OneDrive" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-OfflineFiles" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-NFS" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-NetworkDiagnostics" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Network-QoS" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MRT10" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MobileBroadband" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-EnergyEstimationEngine" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Networking-MobileBroadbandApi" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-PointOfService" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-ContentDeliveryManager" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-DataCenterBridging" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Links" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Migration" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MobileCore" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-PeerDist" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SnippingTool" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TerminalServices" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TS" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Provisioning" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-LanguageEnablingComponents" /r
install_wim_tweak.exe /o /c "Microsoft-Xbox" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TroubleShooting" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-TroubleShooting" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-LanguageFeatures" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Legacy" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-SpeechComponents" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Gaming" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Indexer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-BioEnrollment" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Biometrics" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Printing-XPSServices" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Xps" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Geolocation" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Compression" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-BusinessScanning" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MediaPlayer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WindowsMediaPlayer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-VirtualPC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-VirtualXP" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SystemRestore" /r
install_wim_tweak.exe /o /c "Server-Help" /r
install_wim_tweak.exe /o /c "Sensors-Universal" /r
install_wim_tweak.exe /o /c "MultiPoint-Help" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WordBreaking" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WorkplaceJoin" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WinSATMediaFiles" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WinOcr" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WebcamExperience" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Virtualization" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TextPrediction" /r
install_wim_tweak.exe /o /c "HyperV" /r
install_wim_tweak.exe /o /c "Microsoft-Hyper" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-HyperV" /r
install_wim_tweak.exe /o /c "Media-FaceAnalysis" /r
install_wim_tweak.exe /o /c "Media-Ocr" /r
install_wim_tweak.exe /o /c "Microsoft-Mobile" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-AllJoyn" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-AllowTelemetry" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-BITS" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-CameraCaptureUI" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Connectivity-NFC" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Connectivity-Serial" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-DebugCore" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-InkPlatform" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Maps" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Miracast" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Multimedia-CastingCommon" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Multimedia-CastingReceiver" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Multimedia-CastingTransmitter" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-NowPlayingSessionManager" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-RemoteDesktopServices" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Sensors" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Tethering" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-UserDataAccess" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-Wallet" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-WebService" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-3DAudio" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-AppCompat" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-BITS" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Browser" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Casting" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-CoreSystem-DebugTransports" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Help" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-WMIPerf" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-IIS-WebServer" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Killbits" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Lxss" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Media-Streaming" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MiracastView" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-MobilePC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Shell-HomeGroup" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Network-Connectivity-Assistant" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-QuickAssist" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-RemoteAssistance" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-RemoteFX" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-RemoteDesktop" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TabletPC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SNMP" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Skype" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Shell-SettingSync" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-AllowTelemetry" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-TroubleShooting" /r
install_wim_tweak.exe /o /c "Microsoft-OneCore-TroubleShooting" /r
install_wim_tweak.exe /h /o /l